server:
  port: 8001
spring:
  application:
    name: cloud-payment-hystrix-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    #别名
    instance-id: payment-hystrix-8001
    #访问路径显示IP
    prefer-ip-address: true
    #Eureka客户端向服务端发心跳的时间 默认30s
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端最后一次收到心跳后等待上限 超过2s 说明挂了 默认是90s
    lease-expiration-duration-in-seconds: 2